name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js (matches Lambda runtime)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 3️⃣ Install dependencies in server folder
      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      # 4️⃣ Build TypeScript project
      - name: Build project
        working-directory: ./server
        run: npm run build

      # 5️⃣ Prepare deployment zip (dist + node_modules at root)
      - name: Zip deployment package
        working-directory: ./server
        run: |
          rm -f ../function.zip
          mkdir -p deploy_temp
          cp -r dist/* deploy_temp/
          cp -r node_modules deploy_temp/
          cd deploy_temp
          zip -r ../../function.zip .
          cd ..
          rm -rf deploy_temp

      # 6️⃣ Deploy to Lambda
      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: instasip-server
          handler: "lambda.lambdaHandler"
          zip_file: function.zip
          publish: true
