name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Build project
        working-directory: ./server
        run: npm run build

      - name: Zip deployment package
        working-directory: ./server
        run: |
          # Remove old zip if exists
          rm -f ../function.zip
          # Zip compiled JS
          cd dist
          zip -r ../../function.zip . 
          cd ..
          # Include node_modules
          zip -r ../../function.zip node_modules

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: instasip-server
          handler: "lambda.handler"
          zip_file: function.zip
          publish: true
