name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Build project
        working-directory: ./server
        run: npm run build

      - name: Zip files
        working-directory: ./server
        run: zip -r ../function.zip . -x "*.git*" "node_modules/aws-sdk/*"

      - name: Deploy to Lambda
        uses: appleboy/lambda-action@v1.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: instasip-server
          zip_file: function.zip
